### ISSUE TITLE
Can I visit a string by index?

### ISSUE THREAD

**Issue by duoduo70** [Enalye/grimoire#10]
Like a list, like dlang, can I visit a string by index instead of slice function?

**Comment by Enalye** [comment]
Strings in grimoire are not lists, they are UTF-8 internally which means that each codepoint can be from 1 up to 4 bytes each.
Indexing directly a string which contains non-ascii characters would lead to errors.

If you want to treat it as a list, you can, you just have to convert it to one:
```
var str = "Saluton al ĉiuj 皆さん";
var lst = str as<[char]>;
lst.print; // -> [S, a, l, u, t, o, n,  , a, l,  , ĉ, i, u, j,  , 皆, さ, ん]
lst[-3] = 'p';
lst.print; // -> [S, a, l, u, t, o, n,  , a, l,  , ĉ, i, u, j,  , p, さ, ん]
str = lst; // We can convert it back now
```
char is 4 bytes so it can contains every codepoints available

You can also iterate through the string for each byte or char in it with `chars(string)` and `bytes(string)`:
```
var str = "Saluton al ĉiuj 皆さん";
// For each character
for(ch, str.chars) {
    ch.print;
}
// For each byte
for(b, str.bytes) {
    b.print;
}
```

The slice function works by index too, but it allows you to get more than 1 byte depending on the size of the codepoint.
If you give it wrong values, it’ll try to correct itself and make the indexes fall within the next codepoint boundaries.

Handling strings isn’t easy and I doubt the way I implemented them is perfect, but unfortunately there is no good answer to that. You have to choose between O(n) indexing, or having UTF-32 strings which would break on non-UTF-32 text (and even then, we could argue about codepoints not being true character (whichever your definition of a character is)).

The safest I choice believe now, is to not treat (UTF-8) string as a special list of 'characters' but an opaque type which you have to explicitly convert to a list if you whish to treat it as such. It’s the only way grimoire can somewhat garantee that 'characters' works the way the user expects it.

I think that several modern languages (like Rust) also chose to work this way.

Sorry for the long post, it’s a very complicated subject and trust me, I spent a lot of time banging my head on the wall.

**Comment by duoduo70** [comment]
Thank you very much
