### ISSUE TITLE
(Question) What's the state of this project?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Enalye/grimoire#3]
Which features are implemented?
Would you recommend this for use in production?

**Comment by Enalye** [comment]
I wouldn't recommend this in production. As it is, it's mostly a hobby language for use in plugin systems/gamedev scripting. Its specifications can change any time and it may have a lot of bug/crash.
Furthermore, its missing a lot (the standard library is lacking, documentation is lacking, no debugging tools, etc).
So, for a language, it can be best described as a prototype.
Don't want to discourage you but don't use it in a risky professional project.

**Comment by LunaTheFoxgirl** [comment]
Hm fair nuff, was looking for alternatives to my own scripting language; due to a setback caused by a dependency I was using (llvm-d). Mainly for scripting cutscenes in a game I'm making.

Though I guess I should get back to working on copperlang then xP

Thanks for answering my question :)

I will fork this repo to the org of my game dev team, in case we decide to use it and just go with pulling in changes occasionally.
