### ISSUE TITLE
I do not know how can create an event with parameters.

### ISSUE THREAD

**Issue by duoduo70** [Enalye/grimoire#6]
Hello! I want to create an event with a parameter.
My code:

![image](https://user-images.githubusercontent.com/81518666/215965264-9be728fd-91c1-40b2-be60-b4a14aeb24bd.png)

And my GR code:
![image](https://user-images.githubusercontent.com/81518666/215965326-093cadb7-9da2-4302-a9b9-4b9232abfe74.png)

I get an error:
![image](https://user-images.githubusercontent.com/81518666/215965421-ba947cb2-3c3c-4f5d-a0e1-c8b2de1d47ae.png)

I do not know why I cannot create it.
Can you help me?
Thank you very much!

**Comment by Archivist062** [comment]
Hello,

You made a mistake in the event declaration:

```
event main(string a) {
```

Should be

```
event main(a : string) {
```

I hope you have good fun!

**Comment by duoduo70** [comment]
Oh, Thank you!!

**Comment by Enalye** [comment]
Hello !
The documentation may not be up to date, i’ll update it soon.

Also, you can now call an event with its parameters directly like this:
```d
engine.callEvent("main", [grString], [grValue("Hello World")]);
```
Or check its presence with:
```d
engine.hasEvent("main", [grString]);
```
Without having to handle name mangling manually.

Have a nice day !
