### ISSUE TITLE
Feature request: load, compile and run scripts from memory

### ISSUE THREAD

**Issue by mbierlee** [Enalye/grimoire#7]
Currently the compiler is very file/filesystem oriented. In some environment the host application might need to load files in an alternative way. The host application might also want to pre-process or generate the script before compilation/usage.

Could it be possible to refactor the compiler in such a way that you can also directly feed it code as a string?

**Comment by Enalye** [comment]
Hello, this is a very good idea.
I just added a commit with this feature: 59c51b0981a0a580f614581744c01d1ba58fbfbf
I haven't tested everything but it should work.

Basically I replaced `GrCompiler.compileFile()` with `GrCompiler.compile()` which no longer takes a filepath.
Instead I added `addFile` and `addSource` methods that should be called before `compile`. It should be what you're looking for.

Here's an exemple:
```d
GrCompiler compiler = new GrCompiler;
compiler.addLibrary(grLoadStdLibrary());

// Here you can add as many string based source code as you want
compiler.addSource(`
export func foo()(string) {
    return "Hello World !";
}`);
compiler.addSource(`
event main() {
    foo().print;
}`);
// Adding files works too
compiler.addFile("script/test.gr");

// Then, we compile
GrBytecode bytecode = compiler.compile();
```

**Comment by mbierlee** [comment]
Thank you for considering my suggestion. Grimoire is a very nice scripting language since it stays close to D (with a dash of Go).

How do imports work? Or is all added code considered to be part of one file?

**Comment by Enalye** [comment]
[Imports](https://enalye.github.io/grimoire/#/en/lang/import) works like `compiler.addFile` internally, it ensures that a particular file can only be added once.

Unlike in D, there is no concept of module.

However, every symbols (including class fields) are private to the file that declared it.
To make them visible to other file, one has to add `export` before it. (like in the example in the comment above where `foo()` is exported in the first `addSource` and referenced in the second `addSource`).

(Note that symbols added from a library using the API is considered visible to all file)
